### ISSUE TITLE
Theory behind the code

### ISSUE THREAD

**Issue by TrinhNC** [yoyoberenguer/Fisheye#1]
Thank you for the code. May I ask you for the reference of the method that you implemented? Thank you in advance!

**Comment by yoyoberenguer** [comment]
Hi, 
Please have a look to following links, 
https://tannerhelland.com/2013/02/11/simple-algorithm-correcting-lens-distortion.html
http://popscan.blogspot.com/2012/04/fisheye-lens-equation-simple-fisheye.html
